### PR TITLE
Re-enable scepter to deploy CF templates

### PR DESCRIPTION
**Pull request by zaro0508**
The current build scripts are not longer supported due to
underlying Bridge infra changes.  Use sceptre to deploy
CF templates going forward.

### CODE REVIEW

**Comment by DwayneJengSage** [comment]
Are we sure that the configuration error we saw last time is unrelated to scepter?

**Comment by zaro0508** [comment]
What error are you referring to specifically?

**Comment by DwayneJengSage** [comment]
BridgeWorker-Develop was deployed with UAT configs. According to the logs,
this happened from when Scepter was deployed and lasted until I nuked
Develop and rebuilt it from a previous changelist.

I know "post hoc ergo propter hoc" is a fallacy, but we should at least
perform the due diligence before we push this change out again.

**Comment by zaro0508** [comment]
Could you please verify params are what you expect in env_var and env_var.secret files?  then i can run a test to make sure that the `*_develop` vars will get deployed BridgeWorker develop env.

**Comment by DwayneJengSage** [comment]
The obvious one was that env was "uat" instead of "develop" as expected.

**Comment by zaro0508** [comment]
I deployed to bridgeworker-develop env from my laptop using this PR & scepter.   sceptre responded with  `No updates to perform` which confirms that scepter is deploying with the exact same configs which currently exists in bridgeworker-develop env....   

(sceptredev) ~/w/BridgeWorkerPlatform-infra ❯❯❯ sceptre --var "profile=bridge.prod.travis" --var "region=us-east-1" launch-env develop
[2018-06-13 17:04:27] - sceptre.stack - develop/bridgeworker - Launching stack
[2018-06-13 17:04:27] - sceptre.stack - develop/bridgeworker - Stack is in the CREATE_COMPLETE state
[2018-06-13 17:04:27] - sceptre.stack - develop/bridgeworker - Updating stack
[2018-06-13 17:04:29] - sceptre.stack - develop/bridgeworker - No updates to perform.

**Comment by DwayneJengSage** [comment]
Does Scepter update Elastic Beanstalk configs? I can confirm that our previous script wouldn't update Elastic Beanstalk configs even if the env is out of sync with the Git repo. (This is why I had to nuke the env, app, and Cloud Formation template.)

**Comment by zaro0508** [comment]
Both, the previous script and Sceptre uses the boto3 APIs[1] and there isn't an option in the API to tell CF how to handle out of sync situations.  Therefore there should be no difference between using the two to deploy CF templates.   Also we should try to avoid drift due to manual changes.   The configs and templates in GIT should be our source of truth and all changes should go thru GIT. 

[2] https://boto3.readthedocs.io/en/latest/reference/services/cloudformation.html#CloudFormation.Client.update_stack

**Comment by DwayneJengSage** [comment]
Can we try deploying to a clean environment to verify that it creates the env with the right configs?

**Comment by zaro0508** [comment]
Done, created `bridgeworker-foo` with `*_develop` configs.  could you please verify.

**Review by DwayneJengSage — APPROVED** [review]
Looks good. Approved.

**Pull request merged**
